name: flutter_google_gemini_platform_interface
description: A flutter plugin that implements Google's Gemini AI
version: 0.0.1
homepage: https://github.com/bensonarafat/flutter_google_gemini
repository: https://github.com/bensonarafat/flutter_google_gemini
issue_tracker: https://github.com/bensonarafat/flutter_google_gemini/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0